# Generated by Django 3.2.3 on 2021-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210521_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato_evento',
            name='statusOld',
            field=models.IntegerField(blank=True, choices=[(1, 'Em vigor'), (2, 'Desativado Temporario'), (3, 'Cancelado')], default=None, null=True),
        ),
    ]
